dependencies:
  # - <organization/repo>@<version>.  when compiled, contracts will be stored in dependencies folder
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
#when script is run grab env variables from .env
dotenv: .env

networks:
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
#wallet for defining address to be retrieved from env file
wallets:
  #using curly braces, the variable will be trasformed to its env equivalent
  from_key: ${PRIVATE_KEY}
